/**
 * MerlinSuggestions - Predefined suggestion pools for each category
 * 100 suggestions per category, randomly cycled
 */

export const SUGGESTIONS = {
    item: [
        // Weapons (25)
        "Create a fire sword that ignites enemies on hit",
        "Make a lightning hammer that strikes with thunder",
        "Craft an ice blade that freezes targets",
        "Forge a void dagger that teleports you behind enemies",
        "Create a rainbow sword that changes color with each swing",
        "Make a gravity hammer that launches enemies skyward",
        "Craft a shadow blade that becomes stronger at night",
        "Forge a crystal sword that shoots energy beams",
        "Create a dragon slayer sword with bonus damage to dragons",
        "Make a music sword that plays notes when swinging",
        "Craft a boomerang blade that returns to you",
        "Forge a chain lightning sword that arcs between enemies",
        "Create a poison dagger with damage over time",
        "Make a vampire sword that heals you on hit",
        "Craft a explosive sword that causes small explosions",
        "Forge a wind blade that creates gusts of air",
        "Create a magma sword dripping with lava",
        "Make a star blade made of pure starlight",
        "Craft a bone sword from ancient dragon bones",
        "Forge a singing sword that hums battle melodies",
        "Create a pixelated retro sword",
        "Make a candy cane sword for festive combat",
        "Craft a rubber sword that bounces off targets",
        "Forge a glass sword that shatters dramatically",
        "Create a laser sword with a glowing energy blade",

        // Wands & Staves (25)
        "Make a wand that shoots fireballs",
        "Create a staff that summons lightning bolts",
        "Craft a wand that turns blocks into gold",
        "Make a healing staff that restores health",
        "Create a wand that spawns friendly creatures",
        "Craft a time wand that slows nearby enemies",
        "Make a gravity wand that lifts objects",
        "Create a nature staff that grows instant trees",
        "Craft a water wand that creates waves",
        "Make an earth staff that raises stone walls",
        "Create a wind wand that pushes things away",
        "Craft a necromancer staff that summons skeletons",
        "Make a charm wand that befriends hostile mobs",
        "Create a duplication wand that copies items",
        "Craft a shrinking wand that makes things tiny",
        "Make a growth wand that enlarges creatures",
        "Create a portal wand that opens mini portals",
        "Craft a rainbow wand that shoots colorful beams",
        "Make a music wand that creates sound effects",
        "Create a weather wand that changes the sky",
        "Craft a love wand that makes creatures follow you",
        "Make a chaos wand with random effects",
        "Create a frost staff that creates ice paths",
        "Craft a sun staff that brightens dark areas",
        "Make a moon wand that works best at night",

        // Tools & Equipment (25)
        "Create a grappling hook for climbing",
        "Make a jetpack for flying around",
        "Craft a super pickaxe that mines instantly",
        "Create boots that let you walk on water",
        "Make a parachute for safe falling",
        "Craft a compass that points to treasure",
        "Create gloves that let you climb walls",
        "Make a backpack that holds infinite items",
        "Craft a lantern that never goes out",
        "Create a fishing rod that catches rare fish",
        "Make a shovel that digs in all directions",
        "Craft an axe that chops whole trees at once",
        "Create a magnifying glass that reveals secrets",
        "Make a telescope that sees through walls",
        "Craft a umbrella that protects from all weather",
        "Create roller skates for super speed",
        "Make a pogo stick for bouncy jumping",
        "Craft a hoverboard for smooth gliding",
        "Create a diving helmet for underwater breathing",
        "Make a heat suit for walking in lava",
        "Craft a cold suit for freezing biomes",
        "Create night vision goggles",
        "Make a metal detector for finding ores",
        "Craft a bug net for catching creatures",
        "Create a lasso for roping animals",

        // Consumables & Potions (25)
        "Make a speed potion that doubles movement",
        "Create a strength potion for extra damage",
        "Craft an invisibility potion",
        "Make a flight potion for temporary flying",
        "Create a giant potion that makes you huge",
        "Craft a tiny potion that shrinks you",
        "Make a fire resistance potion",
        "Create a water breathing potion",
        "Craft a night vision potion",
        "Make a healing potion that restores full health",
        "Create a mana potion for magic users",
        "Craft a luck potion for better drops",
        "Make a magnet potion that attracts items",
        "Create a bouncy potion for super jumping",
        "Craft a ghost potion to walk through walls",
        "Make a transformation potion to become an animal",
        "Create a rage potion for berserker mode",
        "Craft a calm potion that pacifies enemies",
        "Make a glowing potion that lights you up",
        "Create a shadow potion for stealth",
        "Craft a clone potion that creates a decoy",
        "Make a swap potion to switch places with target",
        "Create a random potion with surprise effects",
        "Craft an antidote for all negative effects",
        "Make an immortality elixir for temporary invincibility"
    ],

    creature: [
        // Dragons & Flying (20)
        "Create a friendly dragon that follows me",
        "Spawn a baby phoenix that leaves fire trails",
        "Make a cloud creature I can ride",
        "Create a flying carpet companion",
        "Spawn a pegasus with rainbow wings",
        "Make a floating jellyfish pet",
        "Create a tiny helicopter drone buddy",
        "Spawn a griffin that guards me",
        "Make a fairy that heals me over time",
        "Create a will-o-wisp that lights the way",
        "Spawn a flying whale in the sky",
        "Make a bat companion that scouts ahead",
        "Create a hummingbird that collects flowers",
        "Spawn a dragon that breathes ice instead of fire",
        "Make a floating eye that watches for danger",
        "Create a spirit owl for nighttime",
        "Spawn a sky serpent that coils around me",
        "Make a hot air balloon creature",
        "Create a paper airplane that's alive",
        "Spawn a flying saucer pet",

        // Cute & Friendly (20)
        "Spawn a bouncing slime creature",
        "Make a glowing fairy companion",
        "Create a puppy that does tricks",
        "Spawn a kitten with magical powers",
        "Make a bunny that multiplies",
        "Create a hamster in a ball",
        "Spawn a penguin that slides around",
        "Make a baby panda that loves bamboo",
        "Create a fox with nine tails",
        "Spawn a corgi with a crown",
        "Make a hedgehog that rolls into a ball",
        "Create a raccoon that collects shiny things",
        "Spawn a red panda companion",
        "Make a otter that floats on water",
        "Create a capybara friend",
        "Spawn a quokka that always smiles",
        "Make a chinchilla that's super soft",
        "Create a sugar glider that flies to you",
        "Spawn a axolotl with healing powers",
        "Make a seal that claps for you",

        // Monsters & Mythical (20)
        "Create a friendly zombie butler",
        "Spawn a skeleton musician",
        "Make a ghost that tells jokes",
        "Create a vampire that only drinks tomato juice",
        "Spawn a werewolf bodyguard",
        "Make a mummy that wraps gifts",
        "Create a cyclops chef",
        "Spawn a minotaur maze guide",
        "Make a centaur courier",
        "Create a harpy singer",
        "Spawn a medusa hairstylist (safe version)",
        "Make a kraken pool toy",
        "Create a hydra with friendly heads",
        "Spawn a chimera mix-and-match pet",
        "Make a basilisk with sunglasses",
        "Create a cockatrice farmer",
        "Spawn a manticore that purrs",
        "Make a sphinx that tells riddles",
        "Create a yeti snowball fighter",
        "Spawn a sasquatch nature guide",

        // Robots & Mechanical (20)
        "Create a helpful robot companion",
        "Spawn a drone that carries items",
        "Make a mechanical spider builder",
        "Create a robot dog with laser eyes",
        "Spawn a flying security bot",
        "Make a repair bot that fixes things",
        "Create a jukebox robot that plays music",
        "Spawn a cleaning roomba pet",
        "Make a factory arm assistant",
        "Create a hologram buddy",
        "Spawn a nano-swarm companion",
        "Make a steampunk clockwork bird",
        "Create a robot chef that cooks",
        "Spawn a mining robot helper",
        "Make a translation bot for animals",
        "Create a weather prediction bot",
        "Spawn a map-making drone",
        "Make a robot that tells the time",
        "Create a vending machine pet",
        "Spawn an arcade cabinet creature",

        // Elemental & Magic (20)
        "Create a fire elemental pet",
        "Spawn a water spirit companion",
        "Make an earth golem friend",
        "Create an air elemental that fans you",
        "Spawn a lightning sprite",
        "Make an ice elemental for hot days",
        "Create a nature spirit with flowers",
        "Spawn a shadow that mimics you",
        "Make a light orb companion",
        "Create a crystal creature",
        "Spawn a sand elemental sculptor",
        "Make a magma creature for warmth",
        "Create a storm cloud pet",
        "Spawn a rainbow elemental",
        "Make a void creature from darkness",
        "Create a time spirit that rewinds",
        "Spawn a gravity anomaly pet",
        "Make a magnetic creature",
        "Create a sound wave being",
        "Spawn a dream creature from imagination"
    ],

    fix: [
        // Performance (20)
        "Fix any console errors in the game",
        "Optimize creature movement calculations",
        "Fix memory leaks in the render loop",
        "Improve chunk loading performance",
        "Fix lag spikes during combat",
        "Optimize particle effect rendering",
        "Fix slow inventory operations",
        "Improve pathfinding efficiency",
        "Fix frame drops near water",
        "Optimize shadow rendering",
        "Fix garbage collection pauses",
        "Improve texture loading times",
        "Fix slow world generation",
        "Optimize collision detection",
        "Fix network synchronization delays",
        "Improve animation smoothness",
        "Fix audio stuttering issues",
        "Optimize UI rendering performance",
        "Fix slow save/load operations",
        "Improve overall frame rate stability",

        // Bugs & Crashes (20)
        "Fix creatures getting stuck in walls",
        "Debug why entities disappear randomly",
        "Fix the physics glitch when jumping",
        "Resolve texture flickering issues",
        "Fix items falling through the ground",
        "Debug the inventory duplication bug",
        "Fix creatures not responding to damage",
        "Resolve the infinite loop crash",
        "Fix blocks not placing correctly",
        "Debug the respawn location issue",
        "Fix the camera clipping through walls",
        "Resolve the sound not playing bug",
        "Fix keyboard input not registering",
        "Debug the multiplayer desync issue",
        "Fix the lighting calculation errors",
        "Resolve the AI pathfinding failure",
        "Fix the weapon damage not applying",
        "Debug the quest completion bug",
        "Fix the achievement not unlocking",
        "Resolve the settings not saving",

        // Visual & UI (20)
        "Fix UI elements overlapping",
        "Debug the health bar not updating",
        "Fix the minimap orientation",
        "Resolve text rendering issues",
        "Fix the hotbar selection highlight",
        "Debug the tooltip positioning",
        "Fix the menu button hitboxes",
        "Resolve the icon loading failures",
        "Fix the scrollbar behavior",
        "Debug the chat message display",
        "Fix the notification stacking",
        "Resolve the modal backdrop issue",
        "Fix the responsive layout breaks",
        "Debug the animation transitions",
        "Fix the color scheme inconsistencies",
        "Resolve the font rendering blurriness",
        "Fix the progress bar accuracy",
        "Debug the dropdown menu behavior",
        "Fix the tab navigation order",
        "Resolve the focus indicator styling",

        // Gameplay & Logic (20)
        "Fix the day/night cycle timing",
        "Debug the weather system transitions",
        "Fix creature spawning rates",
        "Resolve the experience calculation",
        "Fix the crafting recipe validation",
        "Debug the quest trigger conditions",
        "Fix the combat damage formula",
        "Resolve the movement speed modifiers",
        "Fix the jump height inconsistency",
        "Debug the interaction range detection",
        "Fix the inventory weight limits",
        "Resolve the durability calculations",
        "Fix the spawn point selection",
        "Debug the biome boundary issues",
        "Fix the terrain generation seams",
        "Resolve the structure placement rules",
        "Fix the loot table probabilities",
        "Debug the status effect durations",
        "Fix the cooldown timer accuracy",
        "Resolve the save data corruption",

        // Recent Creations (20)
        "Debug my latest creature creation",
        "Fix issues with the last item I made",
        "Test and verify the recent build",
        "Check for errors in new code",
        "Validate the latest creature behaviors",
        "Fix any broken animations in new entities",
        "Debug the recently added feature",
        "Test the new item functionality",
        "Fix integration issues with new code",
        "Verify the latest changes work correctly",
        "Debug why the new creature won't spawn",
        "Fix the new item not appearing in inventory",
        "Test the edge cases in recent code",
        "Resolve conflicts with existing systems",
        "Fix the new creature's AI behavior",
        "Debug the item's special ability",
        "Test multiplayer sync for new features",
        "Fix performance issues in new code",
        "Validate the new creature's stats",
        "Debug the interaction with other systems"
    ],

    build: [
        // Houses & Homes (20)
        "Build a cozy cottage with a garden",
        "Create a modern minimalist house",
        "Construct a treehouse village",
        "Build an underground bunker home",
        "Create a floating sky mansion",
        "Construct a hobbit hole dwelling",
        "Build a Japanese style house",
        "Create a Victorian mansion",
        "Construct a beach house on stilts",
        "Build a mountain cabin retreat",
        "Create a futuristic dome home",
        "Construct a medieval peasant hut",
        "Build a lighthouse keeper's quarters",
        "Create a desert adobe house",
        "Construct an igloo with interior",
        "Build a mushroom house",
        "Create a crystal palace home",
        "Construct a boat house on water",
        "Build a wizard's tower residence",
        "Create a steampunk airship home",

        // Castles & Fortifications (20)
        "Build a medieval castle with towers",
        "Create a fortress with walls and moat",
        "Construct a Japanese castle (tenshu)",
        "Build a Gothic cathedral castle",
        "Create a fairy tale princess castle",
        "Construct a dark villain's fortress",
        "Build a desert sandstone citadel",
        "Create an ice palace fortress",
        "Construct a cloud castle in the sky",
        "Build a volcanic lair stronghold",
        "Create a underwater dome fortress",
        "Construct a treant living castle",
        "Build a crystal spire citadel",
        "Create a mechanical clockwork castle",
        "Construct a ancient ruins fortress",
        "Build a bamboo fortress",
        "Create a candy castle",
        "Construct a bone castle",
        "Build a glass and steel modern castle",
        "Create a rainbow bridge castle",

        // Towns & Cities (20)
        "Build a small farming village",
        "Create a bustling market square",
        "Construct a harbor town with docks",
        "Build a mining town with rail system",
        "Create a magical academy campus",
        "Construct a gladiator arena district",
        "Build a thieves' guild hideout",
        "Create a royal palace complex",
        "Construct a temple district",
        "Build a merchant quarter",
        "Create a craftsman's workshop row",
        "Construct a tavern and inn",
        "Build a town hall and plaza",
        "Create a prison and courthouse",
        "Construct a hospital and apothecary",
        "Build a stable and animal pens",
        "Create a watchtower network",
        "Construct a sewer system",
        "Build a graveyard and crypt",
        "Create a park and fountain area",

        // Monuments & Landmarks (20)
        "Build a golden pyramid",
        "Create a towering obelisk",
        "Construct a giant statue",
        "Build a colosseum arena",
        "Create a lighthouse beacon",
        "Construct a great library",
        "Build a massive bridge",
        "Create a hanging gardens terrace",
        "Construct a clock tower",
        "Build a windmill farm",
        "Create a water wheel complex",
        "Construct a astronomical observatory",
        "Build a memorial monument",
        "Create a victory arch",
        "Construct a bell tower",
        "Build a giant sundial",
        "Create a hedge maze",
        "Construct a amphitheater",
        "Build a ancient temple ruins",
        "Create a monolithic stone circle",

        // Fantasy & Themed (20)
        "Build a dragon's lair cave",
        "Create a witch's cottage",
        "Construct a pirate ship",
        "Build a space station",
        "Create a underwater city dome",
        "Construct a giant robot statue",
        "Build a mushroom kingdom",
        "Create a candy land village",
        "Construct a haunted mansion",
        "Build a circus big top",
        "Create a roller coaster",
        "Construct a theme park entrance",
        "Build a movie theater",
        "Create a sports stadium",
        "Construct a race track",
        "Build a zoo with enclosures",
        "Create an aquarium building",
        "Construct a museum gallery",
        "Build a art deco skyscraper",
        "Create a neon cyberpunk street"
    ],

    custom: [
        // Creative & Fun (25)
        "Surprise me with something cool!",
        "Create something you think would be fun",
        "Make something that will make me laugh",
        "Build something totally unexpected",
        "Show me your most creative idea",
        "Create something magical and mysterious",
        "Make something that defies physics",
        "Build a scene from my favorite movie",
        "Create an optical illusion",
        "Make something that tells a story",
        "Build a puzzle for me to solve",
        "Create a mini-game within the world",
        "Make an interactive art installation",
        "Build something that moves on its own",
        "Create a chain reaction machine",
        "Make a music-playing contraption",
        "Build a fireworks display",
        "Create a light show",
        "Make a fountain with patterns",
        "Build a roller coaster ride",
        "Create a haunted experience",
        "Make a treasure hunt setup",
        "Build an escape room",
        "Create a battle arena",
        "Make a racing circuit",

        // World Changes (25)
        "Change the world to nighttime",
        "Make it rain in the area",
        "Create a thunderstorm",
        "Turn day into eternal sunset",
        "Make snow fall everywhere",
        "Create a foggy atmosphere",
        "Change the sky to space theme",
        "Make everything underwater themed",
        "Create a volcanic apocalypse",
        "Turn the world into candy land",
        "Make a rainbow appear",
        "Create northern lights in the sky",
        "Change gravity to moon level",
        "Make time move faster",
        "Create a matrix-style effect",
        "Turn the world black and white",
        "Make everything glow in the dark",
        "Create a mirror dimension",
        "Change seasons instantly",
        "Make a eclipse happen",
        "Create meteor showers",
        "Turn water into lava (visually)",
        "Make trees grow instantly",
        "Create a sandstorm",
        "Make a blizzard",

        // Gameplay Changes (25)
        "Give me the ability to fly",
        "Make me run super fast",
        "Grant me infinite jump height",
        "Give me invisibility power",
        "Make me invincible temporarily",
        "Give me x-ray vision for ores",
        "Make me able to walk through walls",
        "Grant me teleportation ability",
        "Give me super strength",
        "Make me tiny like an ant",
        "Grant me giant size",
        "Give me the midas touch",
        "Make time freeze around me",
        "Grant me mind control powers",
        "Give me elemental powers",
        "Make me a shapeshifter",
        "Grant me duplication ability",
        "Give me magnetic powers",
        "Make me glow with energy",
        "Grant me shadow form",
        "Give me sonic speed",
        "Make me able to breathe underwater",
        "Grant me fire immunity",
        "Give me ice powers",
        "Make me able to talk to animals",

        // Utility & Helpful (25)
        "Show me what's nearby",
        "Find the nearest village",
        "Locate valuable ores",
        "Show me where enemies are",
        "Find a good building spot",
        "Locate water sources",
        "Show me hidden caves",
        "Find the highest point nearby",
        "Locate all animals in the area",
        "Show me the way home",
        "Create a map of the area",
        "Mark interesting locations",
        "Find rare creatures",
        "Locate dungeons or structures",
        "Show me biome boundaries",
        "Find a safe path through",
        "Locate other players",
        "Show me resource hotspots",
        "Find the best farming spot",
        "Locate fishing spots",
        "Show me all my creations",
        "Find lost items",
        "Locate spawn points",
        "Show me world statistics",
        "Create a summary of my world"
    ]
};

/**
 * Get random suggestions from a category
 * @param {string} category - The category to get suggestions from
 * @param {number} count - Number of suggestions to return (default 3)
 * @param {Set} exclude - Set of suggestions to exclude (for cycling)
 * @returns {string[]} Array of random suggestions
 */
export function getRandomSuggestions(category, count = 3, exclude = new Set()) {
    const pool = SUGGESTIONS[category] || SUGGESTIONS.custom;

    // Filter out excluded suggestions
    let available = pool.filter(s => !exclude.has(s));

    // If we've excluded too many, reset
    if (available.length < count) {
        available = [...pool];
    }

    // Shuffle and take the first 'count'
    const shuffled = available.sort(() => Math.random() - 0.5);
    return shuffled.slice(0, count);
}

/**
 * Get total count of suggestions for a category
 * @param {string} category
 * @returns {number}
 */
export function getSuggestionCount(category) {
    return (SUGGESTIONS[category] || SUGGESTIONS.custom).length;
}

/**
 * Get all categories with their suggestion counts
 * @returns {Object}
 */
export function getCategoryCounts() {
    return {
        item: SUGGESTIONS.item.length,
        creature: SUGGESTIONS.creature.length,
        fix: SUGGESTIONS.fix.length,
        build: SUGGESTIONS.build.length,
        custom: SUGGESTIONS.custom.length
    };
}
