/**
 * Centralized Block IDs for the Minecraft Clone
 * Usage: import { Blocks } from './Blocks.js';
 */
export const Blocks = {
    AIR: 'air',
    WATER: 'water',
    GRASS: 'grass',
    DIRT: 'dirt',
    STONE: 'stone',
    BEDROCK: 'bedrock',
    SAND: 'sand',
    LOG: 'log',
    LEAVES: 'leaves',
    GLASS: 'glass',
    PLANK: 'plank',
    BRICK: 'brick',
    OBSIDIAN: 'obsidian',
    DIAMOND_BLOCK: 'diamond_block',
    GOLD_BLOCK: 'gold_block',
    TNT: 'tnt',
    BOOKSHELF: 'bookshelf',
    CRAFTING_TABLE: 'crafting_table',
    FURNACE: 'furnace',
    COAL_ORE: 'coal_ore',
    IRON_ORE: 'iron_ore',
    GOLD_ORE: 'gold_ore',
    DIAMOND_ORE: 'diamond_ore',
    REDSTONE_ORE: 'redstone_ore',
    EMERALD_ORE: 'emerald_ore',
    DOOR_CLOSED: 'door_closed',
    DOOR_OPEN: 'door_open',
    FENCE: 'fence',
    FLOWER_RED: 'flower_red',
    FLOWER_YELLOW: 'flower_yellow',
    MUSHROOM_RED: 'mushroom_red',
    MUSHROOM_BROWN: 'mushroom_brown',
    LONG_GRASS: 'long_grass',
    FERN: 'fern',
    FLOWER_BLUE: 'flower_blue',
    DEAD_BUSH: 'dead_bush',
    PINE_WOOD: 'pine_wood',
    PINE_LEAVES: 'pine_leaves',
    BIRCH_WOOD: 'birch_wood',
    BIRCH_LEAVES: 'birch_leaves',
    SNOW: 'snow',
    CACTUS: 'cactus',
    SANDSTONE: 'sandstone',
    CLAY: 'clay',
    GRAVEL: 'gravel',
    PUMPKIN: 'pumpkin',
    MELON: 'melon',
    MYCELIUM: 'mycelium',
    IRON_BARS: 'iron_bars',
    WINDOW_FRAME: 'window_frame',
    LADDER: 'ladder',
    TORCH: 'torch',
    FIRE: 'fire',
    FIRE: 'fire',
    SIGN: 'sign',
    THRUSTER: 'thruster',
    SURVIVAL_BLOCK: 'survival_block',
    MAZE_BLOCK: 'maze_block',
    ESCAPE_ROOM_BLOCK: 'escape_room_block',
    XBOX: 'xbox',
    PARKOUR_BLOCK: 'parkour_block',
    PARKOUR_PLATFORM: 'parkour_platform',
    PLAYGROUND_BLOCK: 'playground_block',
    SLIDE_BLOCK: 'slide_block',
    DISCO_ROOM_BLOCK: 'disco_room_block',
    DISCO_BALL: 'disco_ball',
    MOB_WAVES_BLOCK: 'mob_waves_block',
    DESTINATION_BLOCK: 'destination_block',
    SLIME: 'slime',

    // Starship Enterprise Blocks
    ENTERPRISE_HULL: 'enterprise_hull',
    ENTERPRISE_FLOOR: 'enterprise_floor',
    ENTERPRISE_ENGINE: 'enterprise_engine',
    ENTERPRISE_DISH: 'enterprise_dish_center', // Deflector dish center
    ENTERPRISE_DISH_RING: 'enterprise_dish_ring', // Deflector dish outer
    ENTERPRISE_NACELLE_FRONT: 'enterprise_nacelle_front', // Bussard collector
    ENTERPRISE_NACELLE_SIDE: 'enterprise_nacelle_side', // Warp glow

    // Enterprise Bridge Blocks
    ENTERPRISE_PANEL: 'enterprise_panel',
    ENTERPRISE_SCREEN: 'enterprise_screen',
    ENTERPRISE_CONSOLE: 'enterprise_console',
    ENTERPRISE_CHAIR: 'enterprise_chair'
};
